template = '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubernetes
  name: kubernetes
spec:
  containers:
  - image: kaizenacademy/mycommand:1.0.0
    name: kubernetes
'''

podTemplate(cloud: 'kubernetes', label: 'kubernetes', yaml: template) {
node ("kubernetes") {
    container ("kubernetes") {
    stage ("Checkout SCM") {
        git branch: 'main', url: 'https://github.com/kaizenacademy/jenkins-february-2025.git'
    }
    stage ("Test") {
        sh """
        terraform version
        kubectl version
        helm version
        kubectl get nodes
        """
    }
    }
}
}